version: '3.8'
services:
  postgres:
    image: postgres:14.6
    container_name: picpay-api
    environment:
      POSTGRES_DB: picpay-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local